// AUTO-GENERATED by scripts/gen-wasm-ts.mjs — do not edit.
// Bridge ABI version 1 (see swe_bridge_version).
export type ptr = number; // wasm linear-memory byte offset (0 = null)
export interface SweExports {
  swe_bridge_version(): number;
  swe_session_init(): number;
  swe_session_free(h: number): void;
  swe_version(out_ptr: number, out_len: number): number;
  swe_get_library_path(out_ptr: number, out_len: number): number;
  swe_get_planet_name(h: number, ipl: number, out_ptr: number, out_len: number): number;
  swe_get_current_file_data(h: number, ifno: number, tfstart: number, tfend: number, denum: number): number;
  swe_get_astro_models(samod_ptr: number, samod_len: number, sdet_ptr: number, sdet_len: number, iflag: number): void;
  swe_set_astro_models(samod_ptr: number, samod_len: number, iflag: number): void;
  swe_set_timeout(tsec: number): void;
  swe_set_interpolate_nut(h: number, do_interpolate: number): number;
  swe_sidtime0(h: number, tjd_ut: number, eps: number, nut: number): number;
  swe_sidtime(h: number, tjd_ut: number): number;
  swe_get_ayanamsa(h: number, tjd_et: number): number;
  swe_get_ayanamsa_ut(h: number, tjd_ut: number): number;
  swe_calc_pctr(h: number, tjd: number, ipl: number, iplctr: number, iflag_in: number, xxret: number, serr: number): number;
  swe_solcross(h: number, x2cross: number, jd_et: number, flag_in: number, serr: number): number;
  swe_solcross_ut(h: number, x2cross: number, jd_ut: number, flag_in: number, serr: number): number;
  swe_mooncross(h: number, x2cross: number, jd_et: number, flag_in: number, serr: number): number;
  swe_mooncross_ut(h: number, x2cross: number, jd_ut: number, flag_in: number, serr: number): number;
  swe_mooncross_node(h: number, jd_et: number, flag_in: number, xlon: number, xlat: number, serr: number): number;
  swe_mooncross_node_ut(h: number, jd_ut: number, flag_in: number, xlon: number, xlat: number, serr: number): number;
  swe_helio_cross(h: number, ipl: number, x2cross: number, jd_et: number, iflag_in: number, dir: number, jd_cross: number, serr: number): number;
  swe_helio_cross_ut(h: number, ipl: number, x2cross: number, jd_ut: number, iflag_in: number, dir: number, jd_cross: number, serr: number): number;
  swe_cleanup(h: number): number;
  swe_wasm_alloc(n: number): number;
  swe_wasm_free(ptr: number, n: number): void;
  swe_vfs_register(name_ptr: number, name_len: number, data_ptr: number, data_len: number): number;
  swe_vfs_clear(): void;
  swe_vfs_count(): number;
  swe_vfs_heap_choice(): number;
  swe_julday(year: number, month: number, day: number, hour: number, gregflag: number): number;
  swe_calc_ut(h: number, tjd_ut: number, ipl: number, iflag: number, xx: number, serr: number): number;
  swe_calc(h: number, tjd: number, ipl: number, iflag: number, xx: number, serr: number): number;
  swe_set_topo(h: number, geolon: number, geolat: number, geoalt: number): number;
  swe_set_sid_mode(h: number, sid_mode: number, t0: number, ayan_t0: number): number;
  swe_get_ayanamsa_ex_ut(h: number, tjd_ut: number, iflag: number, daya: number, serr: number): number;
  swe_set_ephe_path(h: number, path: number): number;
  swe_set_jpl_file(h: number, fname: number): number;
  swe_deltat_ex(h: number, tjd: number, iflag: number): number;
  swe_eop_status(h: number): number;
  swe_houses_armc_ex2(h: number, armc: number, geolat: number, eps: number, hsys: number, cusps: number, ascmc: number, serr: number): number;
  swe_house_pos(h: number, armc: number, geolat: number, eps: number, hsys: number, lon: number, lat: number, serr: number): number;
  swe_house_name(hsys: number): number;
  swe_fixstar(h: number, star_ptr: number, star_len: number, tjd: number, iflag: number, xx: number, serr: number): number;
  swe_fixstar_ut(h: number, star_ptr: number, star_len: number, tjd_ut: number, iflag: number, xx: number, serr: number): number;
  swe_fixstar2(h: number, star_ptr: number, star_len: number, tjd: number, iflag: number, xx: number, serr: number): number;
  swe_fixstar2_ut(h: number, star_ptr: number, star_len: number, tjd_ut: number, iflag: number, xx: number, serr: number): number;
  swe_fixstar_mag(h: number, star_ptr: number, star_len: number, mag: number, serr: number): number;
  swe_pheno(h: number, tjd_et: number, ipl: number, iflag: number, attr: number, serr: number): number;
  swe_pheno_ut(h: number, tjd_ut: number, ipl: number, iflag: number, attr: number, serr: number): number;
  swe_nod_aps_ut(h: number, tjd_ut: number, ipl: number, iflag: number, method: number, xnasc: number, xndsc: number, xperi: number, xaphe: number, serr: number): number;
  swe_rise_trans(h: number, tjd_ut: number, ipl: number, star_ptr: number, star_len: number, epheflag: number, rsmi: number, glon: number, glat: number, galt: number, atpress: number, attemp: number, tret: number, serr: number): number;
  swe_rise_trans_true_hor(h: number, tjd_ut: number, ipl: number, star_ptr: number, star_len: number, epheflag: number, rsmi: number, glon: number, glat: number, galt: number, atpress: number, attemp: number, horhgt: number, tret: number, serr: number): number;
  swe_sol_eclipse_when_glob(h: number, tjd: number, ifl: number, ifltype: number, tret: number, backward: number, serr: number): number;
  swe_sol_eclipse_when_loc(h: number, tjd: number, ifl: number, glon: number, glat: number, galt: number, tret: number, attr: number, backward: number, serr: number): number;
  swe_lun_eclipse_when(h: number, tjd: number, ifl: number, ifltype: number, tret: number, backward: number, serr: number): number;
  swe_deltat(h: number, tjd: number): number;
  swe_get_ayanamsa_ex(h: number, tjd_et: number, iflag: number, daya: number, serr: number): number;
  swe_degnorm(x: number): number;
  swe_radnorm(x: number): number;
  swe_difdeg2n(p1: number, p2: number): number;
  swe_difrad2n(p1: number, p2: number): number;
  swe_difdegn(p1: number, p2: number): number;
  swe_deg_midp(x1: number, x0: number): number;
  swe_rad_midp(x1: number, x0: number): number;
  swe_cotrans(xpo: number, xpn: number, eps: number): void;
  swe_cotrans_sp(xpo: number, xpn: number, eps: number): void;
  swe_csnorm(p: number): number;
  swe_difcsn(p1: number, p2: number): number;
  swe_difcs2n(p1: number, p2: number): number;
  swe_csroundsec(x: number): number;
  swe_d2l(x: number): number;
  swe_day_of_week(jd: number): number;
  swe_cs2timestr(t: number, sep: number, suppress_zero: number, out_ptr: number, out_len: number): number;
  swe_cs2lonlatstr(t: number, pchar: number, mchar: number, out_ptr: number, out_len: number): number;
  swe_cs2degstr(t: number, out_ptr: number, out_len: number): number;
  swe_revjul(jd: number, gregflag: number, jyear: number, jmon: number, jday: number, jut: number): void;
  swe_date_conversion(y: number, m: number, d: number, utime: number, c: number, tjd: number): number;
  swe_utc_time_zone(iyear: number, imonth: number, iday: number, ihour: number, imin: number, dsec: number, d_timezone: number, iyear_out: number, imonth_out: number, iday_out: number, ihour_out: number, imin_out: number, dsec_out: number): void;
  swe_split_deg(h: number, ddeg: number, roundflag: number, ideg: number, imin: number, isec: number, dsecfr: number, isgn: number): number;
  swe_get_tid_acc(h: number): number;
  swe_set_tid_acc(h: number, t: number): number;
  swe_set_delta_t_userdef(h: number, dt: number): number;
  swe_set_lapse_rate(h: number, rate: number): number;
  swe_time_equ(h: number, tjd_ut: number, e_out: number, serr: number): number;
  swe_lmt_to_lat(h: number, tjd_lmt: number, geolon: number, tjd_lat: number, serr: number): number;
  swe_lat_to_lmt(h: number, tjd_lat: number, geolon: number, tjd_lmt: number, serr: number): number;
  swe_utc_to_jd(h: number, iyear: number, imonth: number, iday: number, ihour: number, imin: number, dsec: number, gregflag: number, dret0: number, dret1: number, serr: number): number;
  swe_jdet_to_utc(h: number, tjd_et: number, gregflag: number, iyear: number, imonth: number, iday: number, ihour: number, imin: number, dsec: number): number;
  swe_jdut1_to_utc(h: number, tjd_ut: number, gregflag: number, iyear: number, imonth: number, iday: number, ihour: number, imin: number, dsec: number): number;
  swe_close(h: number): number;
  swe_houses_ex2(h: number, tjd_ut: number, iflag: number, geolat: number, geolon: number, hsys: number, cusps: number, ascmc: number, serr: number): number;
  swe_houses(h: number, tjd_ut: number, geolat: number, geolon: number, hsys: number, cusps: number, ascmc: number, serr: number): number;
  swe_houses_ex(h: number, tjd_ut: number, iflag: number, geolat: number, geolon: number, hsys: number, cusps: number, ascmc: number, serr: number): number;
  swe_houses_armc(h: number, armc: number, geolat: number, eps: number, hsys: number, cusps: number, ascmc: number): number;
  swe_calc_sweep(h: number, req: number, out_buf: number, max_f64: number, serr: number): number;
  swe_gauquelin_sector(h: number, t_ut: number, ipl: number, star_ptr: number, star_len: number, iflag: number, imeth: number, glon: number, glat: number, galt: number, atpress: number, attemp: number, dgsect: number, serr: number): number;
  swe_get_orbital_elements(h: number, tjd_et: number, ipl: number, iflag: number, dret: number, serr: number): number;
  swe_orbit_max_min_true_distance(h: number, tjd: number, ipl: number, iflag: number, dmax: number, dmin: number, dtrue: number, serr: number): number;
  swe_azalt(h: number, tjd_ut: number, calc_flag: number, glon: number, glat: number, galt: number, atpress: number, attemp: number, xin: number, xaz: number): number;
  swe_azalt_rev(h: number, tjd_ut: number, calc_flag: number, glon: number, glat: number, galt: number, xin: number, xout: number): number;
  swe_refrac(inalt: number, atpress: number, attemp: number, calc_flag: number): number;
  swe_refrac_extended(inalt: number, geoalt: number, atpress: number, attemp: number, lapse_rate: number, calc_flag: number, dret: number): number;
  swe_sol_eclipse_where(h: number, tjd: number, ifl: number, geopos: number, attr: number, serr: number): number;
  swe_sol_eclipse_how(h: number, tjd: number, ifl: number, glon: number, glat: number, galt: number, attr: number, serr: number): number;
  swe_lun_occult_where(h: number, tjd: number, ipl: number, star_ptr: number, star_len: number, ifl: number, geopos: number, attr: number, serr: number): number;
  swe_lun_occult_when_glob(h: number, tjd: number, ipl: number, star_ptr: number, star_len: number, ifl: number, ifltype: number, tret: number, backward: number, serr: number): number;
  swe_lun_occult_when_loc(h: number, tjd: number, ipl: number, star_ptr: number, star_len: number, ifl: number, glon: number, glat: number, galt: number, tret: number, attr: number, backward: number, serr: number): number;
  swe_lun_eclipse_how(h: number, tjd_ut: number, ifl: number, has_geo: number, glon: number, glat: number, galt: number, attr: number, serr: number): number;
  swe_lun_eclipse_when_loc(h: number, tjd: number, ifl: number, glon: number, glat: number, galt: number, tret: number, attr: number, backward: number, serr: number): number;
  swe_heliacal_ut(h: number, tjd: number, glon: number, glat: number, galt: number, pr: number, te: number, hu: number, vr: number, age: number, snellen: number, bino: number, scope_mag: number, scope_trans: number, opt_flag: number, obj_ptr: number, obj_len: number, evt: number, helflag: number, dret: number, serr: number): number;
  swe_heliacal_pheno_ut(h: number, tjd_ut: number, glon: number, glat: number, galt: number, pr: number, te: number, hu: number, vr: number, age: number, snellen: number, bino: number, scope_mag: number, scope_trans: number, opt_flag: number, obj_ptr: number, obj_len: number, evt: number, helflag: number, darr: number, serr: number): number;
  swe_vis_limit_mag(h: number, tjd: number, glon: number, glat: number, galt: number, pr: number, te: number, hu: number, vr: number, age: number, snellen: number, bino: number, scope_mag: number, scope_trans: number, opt_flag: number, obj_ptr: number, obj_len: number, helflag: number, dret: number, serr: number): number;
  swe_heliacal_angle(h: number, tjd: number, glon: number, glat: number, galt: number, pr: number, te: number, hu: number, vr: number, age: number, snellen: number, bino: number, scope_mag: number, scope_trans: number, opt_flag: number, helflag: number, mag: number, azi_obj: number, azi_sun: number, azi_moon: number, alt_moon: number, dret: number, serr: number): number;
  swe_topo_arcus_visionis(h: number, tjd: number, glon: number, glat: number, galt: number, pr: number, te: number, hu: number, vr: number, age: number, snellen: number, bino: number, scope_mag: number, scope_trans: number, opt_flag: number, helflag: number, mag: number, a1: number, a2: number, a3: number, a4: number, am: number, ret_out: number, serr: number): number;
  swe_get_ayanamsa_name(out_ptr: number, out_len: number): number;
}
export const SWEEP = {
  start_jd: 0,
  step_days: 8,
  steps: 16,
  body_mask: 20,
  flags: 24,
  use_topo: 28,
  topo: 32,
  use_sidereal: 56,
  sidereal: 64,
  size: 88,
} as const;
export const BRIDGE_VERSION = 1;
