// SPDX-License-Identifier: AGPL-3.0-or-later
// Generates test/wasm/swe-bridge.d.ts from src/wasm.zig exports.
// Usage: node scripts/gen-wasm-ts.mjs [--check]
// --check exits 1 when the committed .d.ts is stale (for CI).
// Keeps TS glue in sync with swe_bridge_version(): bump the version in
// wasm.zig on any signature/layout change and regenerate.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const src = fs.readFileSync(path.join(root, 'src/wasm.zig'), 'utf8');
const outPath = path.join(root, 'test/wasm/swe-bridge.d.ts');

function tsType(zig) {
    const t = zig.trim();
    if (t === 'void') return 'void';
    if (t === 'f64') return 'number';
    if (/^(i32|u32|usize|bool|u8|c_int|i64)$/.test(t)) return 'number';
    if (t.includes('*')) return 'number'; // any pointer (0 = null)
    throw new Error(`unmapped Zig type: ${t}`);
}

const fns = [];
const fnRe = /^pub export fn (\w+)\(([^)]*)\)(?: callconv\(\.c\))? (\S+) \{/gm;
let m;
while ((m = fnRe.exec(src)) !== null) {
    const [, name, params, ret] = m;
    const ps = params.trim() === '' ? [] : params.split(',').map((p) => {
        const [pname, ptype] = p.trim().split(/:\s*(.+)/).filter((s, i) => i < 2 || s !== '');
        const [n, ty] = p.trim().split(/\s*:\s*/);
        return `${n.trim()}: ${tsType(ty)}`;
    });
    fns.push(`  ${name}(${ps.join(', ')}): ${tsType(ret)};`);
}

// SweepRequest offsets from the comptime asserts (single source of truth).
const offsets = {};
const offRe = /@offsetOf\(SweepRequest, "(\w+)"\) != (\d+)/g;
while ((m = offRe.exec(src)) !== null) offsets[m[1]] = Number(m[2]);
const sizeM = src.match(/@sizeOf\(SweepRequest\) != (\d+)/);
const versionM = src.match(/pub export fn swe_bridge_version\(\)[^{]+\{\s*return (\d+);/);
if (Object.keys(offsets).length === 0 || !sizeM || !versionM) throw new Error('failed to parse wasm.zig');

const dts = `// AUTO-GENERATED by scripts/gen-wasm-ts.mjs — do not edit.
// Bridge ABI version ${versionM[1]} (see swe_bridge_version).
export type ptr = number; // wasm linear-memory byte offset (0 = null)
export interface SweExports {
${fns.join('\n')}
}
export const SWEEP = {
${Object.entries(offsets).map(([k, v]) => `  ${k}: ${v},`).join('\n')}
  size: ${sizeM[1]},
} as const;
export const BRIDGE_VERSION = ${versionM[1]};
`;

if (process.argv.includes('--check')) {
    const cur = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n') : '';
    if (cur !== dts) { console.error('swe-bridge.d.ts is stale: run node scripts/gen-wasm-ts.mjs'); process.exit(1); }
    console.log('swe-bridge.d.ts in sync');
} else {
    fs.writeFileSync(outPath, dts);
    console.log(`wrote ${outPath} (${fns.length} exports)`);
}
